[package]
name = "commercerack-vstore"
version.workspace = true
edition.workspace = true

[dependencies]
commercerack-db = { path = "../crates/db" }
sqlx.workspace = true
tokio.workspace = true
serde.workspace = true
anyhow.workspace = true
